### ISSUE TITLE
Support for @module

### ISSUE THREAD

**Issue by BjornHansson** [phasebash/jsdoc3-maven-plugin#29]
Do not know if anyone is working with this project anymore. But is it possible to get this to work better with RequireJS? Using the @module http://usejsdoc.org/tags-module.html.

**Comment by phasebash** [comment]
Sure.  We'd need to update the jsdoc3 version from 3.2 to 3.3.  If you would like to attempt this and submit a pull request I would be delighted.  Otherwise, I will have time to look at this over the weekend.  Just a warning if you try, I attempted the update a few months ago and it broke the runtime, so it might not be as simple as changing the version in the root POM.

**Comment by phasebash** [comment]
This should be done in 1.2.0 which was just released.
